syntax = "proto3";

// 根据具体的微服务名称做更改
package grpc_kit.api.known.admin.v1;

option go_package = "github.com/grpc-kit/pkg/api/known/admin/v1;adminv1";

import "known/admin/v1/auth.proto";
import "known/admin/v1/config.proto";

service KnownAdmin {
  rpc GetConfig(GetConfigRequest) returns (GetConfigResponse);
  rpc CreateAuthLogin(CreateAuthLoginRequest) returns (CreateAuthLoginResponse);
  rpc GetAuthProviders(GetAuthProvidersRequest) returns(GetAuthProvidersResponse);
  rpc UpsertAuthProviders(UpsertAuthProvidersRequest) returns(UpsertAuthProvidersResponse);
}