syntax = "proto3";

// 根据具体的微服务名称做更改
package grpc_kit.api.known.admin.v1;

option go_package = "github.com/grpc-kit/pkg/api/known/admin/v1;adminv1";

import "google/protobuf/empty.proto";

import "known/admin/v1/common.proto";
import "known/admin/v1/auth.proto";
import "known/admin/v1/menu.proto";
import "known/admin/v1/config.proto";
import "known/admin/v1/department.proto";
import "known/admin/v1/security.proto";
import "known/admin/v1/user.proto";
import "known/admin/v1/roles.proto";

service KnownAdmin {
  rpc GetConfig(GetConfigRequest) returns (GetConfigResponse);
  // 认证鉴权
  rpc CreateAuthLogin(CreateAuthLoginRequest) returns (CreateAuthLoginResponse);
  rpc CreateAuthToken(CreateAuthTokenRequest) returns (CreateAuthTokenResponse);
  rpc ListAuthProviders(ListAuthProvidersRequest) returns(ListAuthProvidersResponse);
  rpc UpsertAuthProviders(UpsertAuthProvidersRequest) returns(UpsertAuthProvidersResponse);
  rpc GetAuthCallback(GetAuthCallbackRequest) returns(GetAuthCallbackResponse);
  rpc ListMenus(ListMenusRequest) returns(ListMenusResponse);
  rpc ListRoles(ListRolesRequest) returns(ListRolesResponse);
  // 部门相关
  rpc CreateDepartment(CreateDepartmentRequest) returns(Department);
  rpc ListDepartments(ListDepartmentsRequest) returns(ListDepartmentsResponse);
  rpc DeleteDepartment(DeleteDepartmentRequest) returns(google.protobuf.Empty);
  rpc UpdateDepartment(UpdateDepartmentRequest) returns(Department);
  // 用户相关
  rpc ListUsers(ListUsersRequest) returns(ListUsersResponse);
  rpc CreateUser(CreateUserRequest) returns(User);
  rpc UpdateUser(UpdateUserRequest) returns(User);
  // 安全相关
  rpc CreateSecurityKey(CreateSecurityKeyRequest) returns(SecurityKey);
  rpc GetOAuth2Discovery(google.protobuf.Empty) returns(OAuth2Discovery);
  rpc GetOAuth2JSONWebKeys(google.protobuf.Empty) returns(OAuth2JSONWebKeys);
}