syntax = "proto3";

// 根据具体的微服务名称做更改
package grpc_kit.api.known.admin.v1;

option go_package = "github.com/grpc-kit/pkg/api/known/admin/v1;adminv1";

// 引入 google 公共类型
import "google/protobuf/timestamp.proto";

message Leader {
  int32 type = 1;
  int32 user_id = 2;
}

// I18NName 国际化名称
message I18NName {
  string zh_cn = 1;
  string en_us = 2;
  string ja_jp = 3;
}

// Address 用户地址
// https://openid.net/specs/openid-connect-core-1_0.html#AddressClaim
message Address {
  string country = 1;
  string postal_code = 2;
  string region = 3;
  string locality = 4;
  string street_address = 5;
}

// PhoneNumber 手机号，以 E.164 格式存储（E.164 = '+' + 国家码 + 本地号码）总长度 ≤ 15 位，如：+8613812345678
message PhoneNumber {
  // 国家码，字符串更通用，例如 "86", "1"
  string country_code = 1;
  // 本地号码，字符串存储，避免丢失前导零
  string national_number = 2;
}

// Department 组织部门实体，树形结构，一个用户仅可在一个部门内
message Department {
  // ID 实体 ID
  int32 id = 1;
  // ParentID 父 ID，为 0 表示顶级菜单
  int32 parent_id = 2;
  // Name 部门名称
  string name = 3;
  // I18nName 国际化名称
  I18NName i18n_name = 4;
  // OrderWeight 菜单排序权重，数字越小越靠前
  int32 order_weight = 5;
  // Leaders 部门领导列表
  repeated Leader leaders = 6;

  // Children 子部门列表
  repeated Department children = 7;
}

// Resource 资源定义，如：菜单等
message Resource {
  // Type 菜单类型
  enum Type {
    TYPE_UNSPECIFIED = 0; // 未指定类型，保留为默认值
    TYPE_MENU_ADMIN = 1;       // 后台菜单
    TYPE_MENU_USER = 2;        // 用户菜单
    // 可以根据需要扩展其他类型，如 MENU_TYPE_API = 3;
  }

  // ID 菜单 ID
  int32 id = 1;
  // ParentID 父菜单 ID，为 0 表示顶级菜单
  int32 parent_id = 2;
  // Name 菜单名称
  string name = 3;
  // Path 菜单路径
  string path = 4;
  // I18NName 国际化名称
  string i18n_name = 5;
  // Icon 菜单图标，通常用于前端展示
  string icon = 6;
  // OrderWeight 菜单排序权重，数字越小越靠前
  int32 order_weight = 7;
  // Type 菜单用途，如后台管理员、前台用户、APP 应用
  Type type = 8;
  // Enabled 菜单是否启用
  bool enabled = 9;
  // HideInMenu 是否在菜单列表中隐藏
  bool hide_in_menu = 10;
  // HideChildrenInMenu 是否在菜单列表中隐藏子菜单
  bool hide_children_in_menu = 11;
  // Children 子菜单列表
  repeated Resource children = 12;
}

// User 用户实体，表示系统中的账号信息
message User {
  // Gender 用户性别
  enum Gender {
    GENDER_UNSPECIFIED = 0;
    GENDER_MALE = 1;
    GENDER_FEMALE = 2;
  }

  // 用户状态（枚举值预计不会太频繁变化）
  // 可以根据业务再增加状态
  enum Status {
    STATUS_UNSPECIFIED = 0;  // 默认值／未知状态
    STATUS_PENDING = 1;      // 待激活／待验证
    STATUS_ACTIVE = 2;       // 正常启用状态
    STATUS_LOCKED = 3;       // 被锁定（如连续密码错误、账号风控等）
    STATUS_DISABLED = 4;     // 禁用（人工停用）
    STATUS_DELETED = 5;      // 软删除
  }

  message Identity {
    string provider_name = 1;
    string provider_user_id = 2;
    string password_hash = 3;
  }

  // ID 用户 ID，全局唯一标识
  int32 id = 1;
  // 用户名，系统登录凭证，通常唯一
  string username = 2;
  // 用户状态，表示当前账号的生命周期阶段
  Status status = 19;
  // 真实姓名，用于实名认证或后台展示
  string realname = 3;
  // 身份证号，用于身份验证（可选）
  string national_id = 4;
  // 昵称，用于社交或前端展示
  string nickname = 5;
  // 个人简介或签名
  string profile = 6;
  // 用户头像 URL
  string picture = 7;
  // 个人网站地址
  string website = 8;
  // 邮箱地址
  string email = 9;
  // 邮箱是否已验证
  bool email_verified = 10;
  // 性别
  Gender gender = 11;
  // 出生日期
  google.protobuf.Timestamp birthday = 12;
  // 时区信息（IANA 时区标识，例如 "Asia/Shanghai"）
  string zoneinfo = 13;
  // 用户偏好的语言与地区（例如 "zh-CN"、"en-US"）
  string locale = 14;
  // 手机号码
  PhoneNumber phone_number = 15;
  // 手机号码是否已验证
  bool phone_number_verified = 16;
  // 地址信息
  Address address = 17;
  // 所属部门
  Department department = 18;
  // 认证信息
  repeated Identity identities = 20;
}

// Role 角色实体，表示用户在系统上的权限和功能
message Role {
  // ID 角色 ID，全局唯一标识
  int32 id = 1;
  // Name 角色名称
  string name = 2;
  // I18NName 角色国际化名称
  I18NName i18n_name = 3;
  string description = 4;
}

// AuthProvider 身份提供商实体，验证用户登录时使用的第三方服务
message AuthProvider {
  // Type 身份提供商类型
  enum Type {
    TYPE_UNSPECIFIED = 0;
    TYPE_LOCAL = 1;
    TYPE_LDAP = 2;
    TYPE_OIDC = 3;
    TYPE_OAUTH2 = 4;
    TYPE_GITHUB = 5;
    TYPE_GOOGLE = 6;
    TYPE_WECHAT = 7;
  }

  // ID 全局唯一标识
  int32 id = 1;
  // Name 身份提供商名称，全局唯一
  string name = 2;
  // Type 身份提供商类型
  Type type = 3;
  // ClientID 身份提供商客户端 ID
  string client_id = 4;
  // ClientSecret 身份提供商客户端密钥
  string client_secret = 5;
  // Enabled 身份提供商是否启用
  bool enabled = 6;
  // RedirectURI 身份提供商回调地址
  string redirect_uri = 7;
  // Scopes 身份提供商授权范围
  string scopes = 8;
  // Issuer 身份提供商标识
  string issuer = 9;
  // 身份提供商授权端点
  string authorization_endpoint = 10;
  // 身份提供商令牌端点
  string token_endpoint = 11;
  // 身份提供商用户信息端点
  string userinfo_endpoint = 12;
}

// Credential 存储凭证信息
message Credential {
  enum Type {
    TYPE_UNSPECIFIED = 0;
    TYPE_API_KEY = 1;      // 普通 API key
    TYPE_JWT = 2;          // JSON Web Token
    TYPE_JWKS = 3;         // JSON Web Key Set
    TYPE_RSA = 4;          // RSA 密钥对
    TYPE_ECDSA = 5;        // ECDSA 密钥对
    TYPE_ED25519 = 6;      // Ed25519 密钥对
    TYPE_SSH_KEY = 7;      // SSH 公私钥
    TYPE_X509 = 8;         // 证书
    TYPE_LICENSE = 9;      // 软件 License
  }

  // Name 凭据名称
  string name = 1;
  // 凭据类型
  Type type = 2;
  // Appid 凭据关联的应用 ID
  string appid = 3;
  // Appkey 凭据关联的密钥
  string appkey = 4;
  // 公钥
  string public_key = 5;
  // 私钥
  string private_key = 6;

  string usage = 7;

  // 过期时间
  google.protobuf.Timestamp expires_at = 8;
}

message OAuth2JSONWebKeys {
  message Key {
    string kty = 1;
    string use = 2;
    string alg = 3;
    string e = 4;
    string n = 5;
    string kid = 6;
  }

  repeated Key keys = 1;
}
