syntax = "proto3";

// 根据具体的微服务名称做更改
package grpc_kit.api.known.admin.v1;

option go_package = "github.com/grpc-kit/pkg/api/known/admin/v1;adminv1";

message LocalConfig {
  ServicesConfig services = 1;
  DiscoverConfig discover = 2;
  SecurityConfig security = 3;
  DatabaseConfig database = 4;
  CacheboxConfig cachebox = 5;
  DebuggerConfig debugger = 6;
  ObjstoreConfig objstore = 7;
  FrontendConfig frontend = 8;
  ObservablesConfig observables = 9;
  CloudEventsConfig cloudevents = 10;
  AutomationsConfig automations = 11;
}

message ServicesConfig {
  string name = 1;
  bool enabled = 2;
}

message DiscoverConfig {
  string name = 1;
  bool enabled = 2;
}

message SecurityConfig {
  string name = 1;
  bool enabled = 2;

  Authentication authentication = 4;
  Authorization authorization = 5;
}

message DatabaseConfig {
  string name = 1;
  bool enabled = 2;

}

message CacheboxConfig {
  string name = 1;
  bool enabled = 2;

}

message DebuggerConfig {
  string name = 1;
  bool enabled = 2;

}

message ObjstoreConfig {
  string name = 1;
  bool enabled = 2;

}

message FrontendConfig {
  string name = 1;
  bool enabled = 2;

}

message ObservablesConfig {
  string name = 1;
  bool enabled = 2;

}

message CloudEventsConfig {
  string name = 1;
  bool enabled = 2;

}

message AutomationsConfig {
  string name = 1;
  bool enabled = 2;

}

message Authentication {
  repeated string insecure_rpcs = 1;
  OIDCProvider oidc_provider = 2;
  repeated BasicAuth http_users = 3;
}

message Authorization {

}

message OIDCProvider {

}

message BasicAuth {
  int64 user_id = 1;
  string username = 2;
  string password = 3;
  string password_hash = 4;
  repeated string groups = 5;
  string tenant = 6;
}

message AuthorizationConfig {

}

message GetConfigRequest {

}

message GetConfigSecurityRequest {

}