syntax = "proto3";

// 根据具体的微服务名称做更改
package grpc_kit.api.known.admin.v1;

option go_package = "github.com/grpc-kit/pkg/api/known/admin/v1;adminv1";

import "google/protobuf/field_mask.proto";

import "known/admin/v1/admin.common.proto";

message ListResourcesRequest {
  // 父资源名称，用于限定范围。
  // 格式示例: "organizations/123" 或 "projects/456"。
  string parent = 1;

  // 每页返回的最大用户数。
  // - 如果未指定，则使用服务端默认值 (如 20)。
  // - 最大不超过 100 (超出时强制截断)。
  int32 page_size = 2;

  oneof pagination {
    // Cursor-based 分页
    string page_token = 3;

    // Offset-based 分页
    int32 offset = 8;
  }

  // 过滤条件，采用 AIP-160 定义的标准 filter 语法。
  // 示例: `email="alice@example.com" AND state="ACTIVE"`
  string filter = 4;

  // 排序规则，指定结果返回顺序。
  // 格式: "field_name [asc|desc], ..."。
  // 示例: "create_time desc, name asc"
  // AIP-132: order_by 是可选字段。
  string order_by = 5;

  // TODO；将来会统一使用 filter 参数实现过滤
  string type = 6;
  string scope = 7;
}

message ListResourcesResponse {
  repeated Resource resources = 1;
}


message CreateResourceRequest {
  Resource resource = 1;
}

message UpdateResourceRequest {
  Resource resource = 1;

  google.protobuf.FieldMask update_mask = 3;
}

message DeleteResourceRequest {
  int32 id = 1;
}