syntax = "proto3";

package grpc_kit.api.known.admin.v1;

option go_package = "github.com/grpc-kit/pkg/api/known/admin/v1;adminv1";

import "known/admin/v1/admin.common.proto";

message GetGlobalSettingsRequest {
  string category = 1;
}

message ListGlobalSettingsRequest {}

message ListGlobalSettingsResponse {
  repeated GlobalSettingCategory categories = 1;
}

message UpdateGlobalSettingsRequest {
  string category = 1;
  repeated UpdateGlobalSetting updates = 2;
}

message UpdateGlobalSettingsResponse {
  GlobalSettingCategory category = 1;
}