// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/v1/example.proto

// TODO; 根据具体的微服务名称做更改

package grpc_kit_api_proto_v1

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ExampleRequest struct {
	// Name 该字段的备注，这里把它设置为必填属性
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Value 该字段的备注，这里设置它默认值为3.14
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *ExampleRequest) Reset()         { *m = ExampleRequest{} }
func (m *ExampleRequest) String() string { return proto.CompactTextString(m) }
func (*ExampleRequest) ProtoMessage()    {}
func (*ExampleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9bcb6e413bba4d7, []int{0}
}
func (m *ExampleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExampleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExampleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExampleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleRequest.Merge(m, src)
}
func (m *ExampleRequest) XXX_Size() int {
	return m.Size()
}
func (m *ExampleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleRequest proto.InternalMessageInfo

func (m *ExampleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExampleRequest) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ExampleResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *ExampleResponse) Reset()         { *m = ExampleResponse{} }
func (m *ExampleResponse) String() string { return proto.CompactTextString(m) }
func (*ExampleResponse) ProtoMessage()    {}
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9bcb6e413bba4d7, []int{1}
}
func (m *ExampleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExampleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExampleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExampleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleResponse.Merge(m, src)
}
func (m *ExampleResponse) XXX_Size() int {
	return m.Size()
}
func (m *ExampleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleResponse proto.InternalMessageInfo

func (m *ExampleResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ExampleRequest)(nil), "grpc.kit.api.proto.v1.ExampleRequest")
	golang_proto.RegisterType((*ExampleRequest)(nil), "grpc.kit.api.proto.v1.ExampleRequest")
	proto.RegisterType((*ExampleResponse)(nil), "grpc.kit.api.proto.v1.ExampleResponse")
	golang_proto.RegisterType((*ExampleResponse)(nil), "grpc.kit.api.proto.v1.ExampleResponse")
}

func init() { proto.RegisterFile("proto/v1/example.proto", fileDescriptor_e9bcb6e413bba4d7) }
func init() { golang_proto.RegisterFile("proto/v1/example.proto", fileDescriptor_e9bcb6e413bba4d7) }

var fileDescriptor_e9bcb6e413bba4d7 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xbf, 0x6b, 0xdb, 0x40,
	0x14, 0xc7, 0xef, 0x85, 0x34, 0x10, 0x41, 0x7f, 0xa0, 0x92, 0x60, 0x42, 0x79, 0x11, 0xa2, 0x43,
	0x16, 0x4b, 0xd8, 0xc9, 0x64, 0xe8, 0x20, 0xd3, 0xfe, 0x03, 0xee, 0xd8, 0xe9, 0x2c, 0xae, 0x17,
	0x11, 0x59, 0x77, 0xb5, 0xce, 0x4e, 0x42, 0x08, 0x84, 0x92, 0xa1, 0x4b, 0xa1, 0x38, 0x9d, 0x0a,
	0x2d, 0x1d, 0xb3, 0x35, 0x9d, 0x1a, 0xda, 0x25, 0xa3, 0x47, 0xd3, 0xc9, 0x63, 0x74, 0x47, 0x12,
	0x8f, 0x19, 0x3b, 0x16, 0x4b, 0x22, 0x38, 0x78, 0x11, 0xef, 0x7d, 0xf5, 0xde, 0xe7, 0xfb, 0x7d,
	0x67, 0xad, 0xca, 0xae, 0x50, 0xc2, 0xef, 0xd7, 0x7c, 0xb6, 0x47, 0x3b, 0x32, 0x66, 0x5e, 0x2e,
	0xd8, 0x2b, 0xbc, 0x2b, 0x43, 0x6f, 0x27, 0x52, 0x1e, 0x95, 0x51, 0xa1, 0x79, 0xfd, 0xda, 0x5a,
	0x95, 0x47, 0x6a, 0xbb, 0xd7, 0xf6, 0x42, 0xd1, 0xf1, 0xb9, 0xe0, 0xc2, 0xcf, 0xff, 0xb4, 0x7b,
	0x6f, 0xf3, 0xae, 0x60, 0x4d, 0xab, 0x62, 0x63, 0xed, 0xc5, 0xbd, 0x71, 0xc1, 0x63, 0x46, 0x65,
	0x94, 0xce, 0x97, 0x3e, 0x95, 0x91, 0x4f, 0x93, 0x44, 0x28, 0xaa, 0x22, 0x91, 0xa4, 0xe5, 0xfa,
	0xeb, 0xd9, 0xf5, 0xae, 0x0c, 0xab, 0x2c, 0x14, 0xe9, 0x7e, 0xaa, 0x58, 0xd9, 0x72, 0xaa, 0xd8,
	0x2e, 0xdd, 0x2f, 0x42, 0x84, 0x55, 0xce, 0x92, 0x6a, 0xba, 0x4b, 0x39, 0x67, 0x5d, 0x5f, 0xc8,
	0x1c, 0x34, 0x0f, 0x75, 0xbf, 0x82, 0xf5, 0xe8, 0x55, 0x71, 0x6b, 0x8b, 0xbd, 0xeb, 0xb1, 0x54,
	0xd9, 0xcf, 0xad, 0xc5, 0x84, 0x76, 0x58, 0x05, 0x1c, 0xd8, 0x58, 0x6e, 0x3e, 0x19, 0x04, 0x0f,
	0xf7, 0x86, 0x70, 0x04, 0xf0, 0x17, 0x72, 0xbd, 0x95, 0x7f, 0xed, 0x75, 0xeb, 0x41, 0x9f, 0xc6,
	0x3d, 0x56, 0x59, 0x70, 0x60, 0x63, 0xa1, 0xb9, 0x3c, 0x08, 0x96, 0x1a, 0x8b, 0x9b, 0x5e, 0x6d,
	0xab, 0x55, 0xe8, 0x8d, 0x97, 0x83, 0x20, 0xb0, 0xd6, 0xeb, 0xab, 0x25, 0xfd, 0xe6, 0xcb, 0xf1,
	0xe4, 0xc7, 0xaf, 0xeb, 0x9f, 0xef, 0x6f, 0xfe, 0x9c, 0x5c, 0x7f, 0x3b, 0x2e, 0x61, 0x75, 0xb4,
	0x9f, 0x1d, 0x38, 0xee, 0xb4, 0x74, 0x1b, 0x8e, 0xbb, 0xcd, 0xe2, 0x58, 0x38, 0xf9, 0x35, 0x3b,
	0x91, 0x72, 0x9d, 0x43, 0xf7, 0x8d, 0xf5, 0xf8, 0x2e, 0x5e, 0x2a, 0x45, 0x92, 0x32, 0xdb, 0x9e,
	0xcd, 0x57, 0xa4, 0x69, 0x6c, 0x0d, 0x82, 0x9a, 0x55, 0x99, 0x35, 0xbb, 0x3a, 0xf9, 0x78, 0xf5,
	0xfb, 0x73, 0x61, 0x56, 0x5f, 0xb1, 0x9f, 0x1e, 0x94, 0x26, 0xee, 0x1d, 0xfd, 0xb0, 0xa9, 0x86,
	0x19, 0xc2, 0x28, 0x43, 0x18, 0x67, 0x08, 0x97, 0x19, 0x92, 0x49, 0x86, 0xe4, 0x36, 0x43, 0xf2,
	0x2f, 0x43, 0x72, 0xa4, 0x91, 0x7c, 0xd0, 0x48, 0x4e, 0x35, 0xc2, 0x99, 0x46, 0x72, 0xae, 0x91,
	0x5c, 0x68, 0x24, 0x43, 0x8d, 0x30, 0xd2, 0x08, 0x63, 0x8d, 0xe4, 0x52, 0x23, 0x4c, 0x34, 0xc2,
	0xed, 0x74, 0xd6, 0x20, 0xf9, 0x64, 0x90, 0x7c, 0x37, 0x48, 0x4e, 0x0d, 0xc2, 0x99, 0x41, 0x38,
	0x37, 0x08, 0x17, 0x06, 0x61, 0x68, 0x90, 0x8c, 0x0c, 0x92, 0xb1, 0x41, 0xd2, 0x5e, 0xca, 0x5f,
	0x7e, 0xf3, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x67, 0x23, 0xc3, 0x6d, 0x02, 0x00, 0x00,
}

func (this *ExampleRequest) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*ExampleRequest)
	if !ok {
		that2, ok := that.(ExampleRequest)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Name != that1.Name {
		if this.Name < that1.Name {
			return -1
		}
		return 1
	}
	if this.Value != that1.Value {
		if this.Value < that1.Value {
			return -1
		}
		return 1
	}
	return 0
}
func (this *ExampleResponse) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*ExampleResponse)
	if !ok {
		that2, ok := that.(ExampleResponse)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Name != that1.Name {
		if this.Name < that1.Name {
			return -1
		}
		return 1
	}
	return 0
}
func (this *ExampleRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExampleRequest)
	if !ok {
		that2, ok := that.(ExampleRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	return true
}
func (this *ExampleResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExampleResponse)
	if !ok {
		that2, ok := that.(ExampleResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	return true
}
func (m *ExampleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExampleRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintExample(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.Value != 0 {
		dAtA[i] = 0x15
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Value))))
		i += 4
	}
	return i, nil
}

func (m *ExampleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExampleResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintExample(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	return i, nil
}

func encodeVarintExample(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ExampleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovExample(uint64(l))
	}
	if m.Value != 0 {
		n += 5
	}
	return n
}

func (m *ExampleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovExample(uint64(l))
	}
	return n
}

func sovExample(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozExample(x uint64) (n int) {
	return sovExample(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ExampleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExample
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExampleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExampleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExample
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExample
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Value = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipExample(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthExample
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthExample
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExampleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExample
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExampleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExampleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExample
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExample
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExample
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExample(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthExample
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthExample
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipExample(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowExample
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExample
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExample
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthExample
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthExample
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowExample
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipExample(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthExample
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthExample = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowExample   = fmt.Errorf("proto: integer overflow")
)
